name: discord
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libmpdec=4.0.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - pthread-stubs=0.3
  - python=3.13.5
  - python_abi=3.13
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - altair==5.5.0
      - attrs==25.3.0
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - click==8.2.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - faiss-cpu==1.11.0
      - filelock==3.18.0
      - fonttools==4.58.4
      - fsspec==2025.5.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - hf-xet==1.1.4
      - huggingface-hub==0.33.0
      - idna==3.10
      - jinja2==3.1.6
      - joblib==1.5.1
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.8
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mpmath==1.3.0
      - narwhals==1.43.0
      - networkx==3.5
      - numpy==2.3.0
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - packaging==24.2
      - pandas==2.3.0
      - pillow==11.2.1
      - protobuf==6.31.1
      - pyarrow==20.0.0
      - pydeck==0.9.1
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.4
      - rpds-py==0.25.1
      - safetensors==0.5.3
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - sentence-transformers==4.1.0
      - six==1.17.0
      - smmap==5.0.2
      - streamlit==1.45.1
      - streamlit-autorefresh==1.0.1
      - sympy==1.14.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tokenizers==0.21.1
      - toml==0.10.2
      - torch==2.7.1
      - tornado==6.5.1
      - tqdm==4.67.1
      - transformers==4.52.4
      - triton==3.3.1
      - typing-extensions==4.14.0
      - tzdata==2025.2
      - urllib3==2.4.0
      - watchdog==6.0.0
